version: '3'
services:
  app1:
    build: .
    environment:
      - APP_NAME=App1
    expose:
      - "3000"  # For internal Docker network
    ports:
      - "3001:3000"  # For direct external API access (optional)



  app2:
    build: .
    environment:
      - APP_NAME=App2
    expose:
      - "3000"
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APP_NAME=App3
    expose:
      - "3000"
    ports:
      - "3003:3000"


  nginx:
    image: nginx:alpine
    # Add explicit CORS environment variables
    environment:
      - CORS_ALLOW_ORIGIN=http://localhost:8080,http://127.0.0.1:8080
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/usr/share/nginx/html
    depends_on:
      - app1
      - app2
      - app3